name = "marksman"
main = "src/index.js"
compatibility_date = "2024-01-01"

# We will bind the KV Namespace in the Cloudflare Dashboard
# This tells Wrangler that the code expects a variable named WHITELIST_KV
[[kv_namespaces]]
binding = "WHITELIST_KV"
id = "e3d984c363ad430a89c2d7624f7d0dda"